# Source: surrealdb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
  labels:
    app.kubernetes.io/name: surrealdb
    app.kubernetes.io/instance: surrealdb
    app.kubernetes.io/version: 2.3.7
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: surrealdb
      app.kubernetes.io/instance: surrealdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: surrealdb
        app.kubernetes.io/instance: surrealdb
    spec:
      serviceAccountName: surrealdb
      securityContext: {}
      containers:
      - name: surrealdb
        securityContext: {}
        image: surrealdb/surrealdb:v2.3.7
        imagePullPolicy: IfNotPresent
        args:
        - start
        env:
        - name: SURREAL_NO_BANNER
          value: 'true'
        - name: SURREAL_PATH
          value: surrealkv://data/db
        - name: SURREAL_LOG
          value: info
        - name: SURREAL_BIND
          value: 0.0.0.0:8000
        - name: SURREAL_AUTH
          value: 'true'
        - name: SURREAL_UNAUTHENTICATED
          value: 'false'
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: surrealdb
