# Source: id.noa.re
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-noa-re
  labels:
    app: id-noa-re
  namespace: idelephant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: id-noa-re
  template:
    metadata:
      labels:
        app: id-noa-re
    spec:
      containers:
      - name: id-noa-re
        image: nresare/idelephant:latest
        args:
        - -c
        - /config/idelephant.toml
        volumeMounts:
        - name: id-noa-re-config
          mountPath: /config
        - name: db-password
          mountPath: /db-password
        - name: email-password
          mountPath: /email-password
      volumes:
      - name: id-noa-re-config
        configMap:
          name: id-noa-re-config
      - name: db-password
        secret:
          secretName: db-password
      - name: email-password
        secret:
          secretName: email-password
